# @name status
# @tag smoke
# @assert status == 200
GET {{base_url}}/status/200
Accept: application/json

###

# @name echo
# @tag smoke
# @depends-on status
# @assert status == 200
# @assert json $.json.client == "verbsmith"
# @capture echoed_client = jsonpath("$.json.client")
POST {{base_url}}/anything
Content-Type: application/json

{"client":"{{client}}"}
